/**
 * This file is automatically generated by jsrepo.
 * Do not edit it manually.
 */

export const DEMO_PATHS = ['add-demo', 'demo-demo'] as const;

export type DemoPath = (typeof DEMO_PATHS)[number];
