import { kebabToPascal } from '../utils/casing';
import type { Output } from 'jsrepo/outputs';
import fs from 'node:fs';
import path from 'node:path';

const EXAMPLES_INDEX_PATH = 'src/lib/examples/index.ts';

export function demoOutput(): Output {
	return {
		output: async (buildResult) => {
			const examples = buildResult.items.flatMap((item) =>
				item.files
					.filter((file) => file.type === 'registry:example')
					.map((file) => {
						const parsed = path.parse(file.path);
						return {
							name: kebabToPascal(parsed.name),
							basePath: parsed.name,
							path: file.path
						};
					})
			);

			const code = `/**
 * This file is automatically generated by jsrepo.
 * Do not edit it manually.
 */

export const DEMO_PATHS = [
	${examples.map((example) => `'${example.basePath}'`).join(', ')}
] as const;

export type DemoPath = typeof DEMO_PATHS[number];
`;
			fs.writeFileSync(EXAMPLES_INDEX_PATH, code);
		},
		clean: async () => {
			if (fs.existsSync(EXAMPLES_INDEX_PATH)) {
				fs.rmSync(EXAMPLES_INDEX_PATH);
			}
		}
	};
}
